spring:
  application:
    name: vibeapp
  datasource:
    url: jdbc:h2:file:/home/bigtiger/workspace/vibe-coding-fullstack/data/testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  sql:
    init:
      mode: never
      data-locations: 

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.vibeapp.post
  configuration:
    map-underscore-to-camel-case: true

debug: true

logging:
  level:
    org.springframework.boot.autoconfigure: debug
  file:
    name: ./logs/app.log

server:
  port: 8080
